[package]
name = "bity-ic-canister-timer-jobs"
version = "0.1.0"
edition = "2021"
description = "Description spécifique de la crate" 
license = "MIT"
repository = "https://github.com/bity/bity_dfinity_library"
keywords = ["dfinity", "internet-computer", "ic", "canister", "subcanister"]
authors = ["Bity Team", "Gautier Wojda <gautier.wojda@bity.com>", "Freddie Hands <freddie.hands@bity.com>", "Victoria Horbunova <victoria.horbunova@bity.com>", "Dustin Becker <dustin.becker@bity.com>"]
documentation = "https://docs.rs/bity-ic-canister-timer-jobs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-cdk-timers = { workspace = true }
serde = { workspace = true }
bity-ic-types = { path = "../types" }
bity-ic-utils = { path = "../utils" }
tracing = { workspace = true }
ic-cdk = { workspace = true }
job_macros = { path = "./job_macros" }

[dev-dependencies]
tokio = {version = "1.39.2", features = ["rt", "macros"]}
