[package]
name = "bity-ic-icrc3-archive-api"
version = "0.1.0"
description = "bity icrc3 archive api"
edition = "2021"

[features]
inttest = []

[workspace]


[dependencies]
bity-ic-types = "0.1.0"
candid = "0.10.13"
icrc-ledger-types = "0.1.8"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.17"
ic-stable-structures = "0.6.7"
sha2 = "0.10"
hex = "0.4.3"
serde_cbor = "0.11"